repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck --severity=error
        language: system
        types: [shell]
        files: \.(sh|bash)$

      - id: tests
        name: run tests
        entry: ./tests/run_tests.sh
        language: system
        pass_filenames: false
        always_run: true
